platform: linux

image_resource:
  type: docker-image
  source: {repository: bitsdock/docker-java-sbt, tag: "latest"}

inputs:
  - name: player-master

outputs:
  - name: assembly-artifacts

run:
  path: ./player-master/devops/pipeline/assembly.sh

