apiVersion: batch/v1
kind: Job
metadata:
  name: mysparksql
spec:
  template:
    metadata:
      name: mysparksql
    spec:
      containers:
      - name: mysparksql
        image: navicore/mysparksql
        env: 
        - name: CASSANDRA_HOST
          value: "<YOUR CASSANDRA HOST>"
        - name: SPARK_MASTER
          value: "spark://<YOUR SPARK MASTER>"
        - name: KEYSPACE
          value: "<YOUR KEYSPACE>"
        - name: TABLE
          value: "<YOUR TABLE>"
      restartPolicy: Never

